### ISSUE TITLE
Spremanje u My Documents

### ISSUE THREAD

**Issue by lovrosverko** [budicmarin/budicMarinXMLIspis#1]
https://github.com/budicmarin/budicMarinXMLIspis/blob/c88e719e621a620ebf856618ff900047a4d2637c/Program.cs#L97

Ne treba "hardcode" put do datoteke za My Documents.

Pogledaj ovo: [https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-5.0](https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-5.0)

**Comment by budicmarin** [comment]
Aha , a jer ja sam stavio zbog toga šmo mi je my documensts na drugom disk i onda sam samo prebacio pinter na taj disk

**Comment by lovrosverko** [comment]
Sve ok, ali dobro je koristiti put prema specijalnim direktorijima kako bi aplikacija radila na bilo kojem računalu s Windowsima.
